apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
jobs:
  gcloud:
    steps:
      - uses: docker://alpine/git:latest
        name: Add cred file
        run: |
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - uses: docker://alpine/git:latest
        name: cat [or od -a]
        run: |
          cd ${HOME}/.kube
          cat config.json
          cd ${HOME}
          ls -la
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: GCLOD
        run: |
          export KUBECONFIG=${HOME}/.kube/config
          echo $KUBECONFIG
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap001 --region us-east1 --project mlcbplatformproject 
          kubectl get namespaces
