apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
jobs:
  job1:
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Add cred file
        run: gcloud auth list
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Add cred file
        run: >
          rm -rf ${HOME}/.kube

          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF

          ${{ secrets.mlcbMultilinePass }}
          
          EOF
          gcloud auth login --cred-file=${HOME}/.kube/config.json
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap001 --region us-east1 --project mlcbplatformproject
          kubectl get namespaces
          kubectl create deployment deployment-mlcb