apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
jobs:
  job1:
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Add cred file
        run: >
          rm -rf ${HOME}/.cred
          mkdir ${HOME}/.cred
          cat > ${HOME}/.cred/cred 
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: auth
        run: >
          cd ${HOME}/.cred
          ls
