apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
jobs:
  checkout:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Check out repo
      - uses: docker://alpine/git:latest
        name: LS
        run: |
          ls
          pwd
  gcloud:
    steps:
      - uses: docker://alpine/git:latest
        name: Add cred file
        run: |
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - uses: docker://alpine/git:latest
        name: cat
        run: |
          cd ${HOME}/.kube
          od -a config.json
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: GCLOD
        run: |
          cd ${HOME}
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap001 --region us-east1 --project mlcbplatformproject 
          kubectl get namespaces          
    needs:
      - checkout
