apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
env:
  APP_NAME: demo-app
  BUILD: "false"
  DEPLOY: "true"
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/helm-install@v1
        name: deployStep
        run: kubectl get namespaces
