apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
jobs:
  job1:
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: step1
        run: gcloud config set project caca
