apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy demo-app
on:
  push:
    branches:
      - "**"
jobs:
  deploy:
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: deployStep
        run: kubectl get namespaces
