apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy to GKE
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  job1:
    steps:
      - uses: docker://golang:1.20
        name: Deploy
        shell: /bin/sh
        run: echo "hello world 23"
    needs:
      - build
